#!/usr/bin/env bash
# Shared helpers for generating and checking the cargo-dist release workflows.
#
# Sourced by regen-dist-release.sh (which writes the committed workflows) and by
# check-dist-release-generated.sh (which verifies them without modifying them).
#
# Callers must `cd` to the repo root before sourcing. The committed config file
# can be overridden via the `dist_config` variable before sourcing.

dist_config="${dist_config:-dist-workspace.toml}"

# The tag-namespace used for the committed dry-run workflow. This value is only a
# filename prefix and (under dispatch-releases) never appears in the generated
# body, so the drift check can substitute a throwaway namespace to redirect
# dist's output away from the committed file while producing identical content.
dry_run_tag_namespace="dist-dry-run"

configured_dist_version() {
  sed -n 's/^[[:space:]]*cargo-dist-version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "${dist_config}" | head -n1
}

dist_version_matches() {
  local expected="$1"
  local actual

  actual="$(dist --version 2>/dev/null || true)"
  [ "${actual}" = "cargo-dist ${expected}" ]
}

ensure_dist() {
  local expected

  expected="$(configured_dist_version)"
  if [ -z "${expected}" ]; then
    echo "Could not read cargo-dist-version from ${dist_config}" >&2
    exit 1
  fi

  if command -v dist >/dev/null 2>&1 && dist_version_matches "${expected}"; then
    return
  fi

  echo "Installing cargo-dist ${expected}..."
  curl --proto '=https' --tlsv1.2 -LsSf \
    "https://github.com/axodotdev/cargo-dist/releases/download/v${expected}/cargo-dist-installer.sh" |
    sh
  export PATH="${HOME}/.cargo/bin:${PATH}"

  if ! command -v dist >/dev/null 2>&1 || ! dist_version_matches "${expected}"; then
    echo "cargo-dist ${expected} was not available after installation" >&2
    exit 1
  fi
}

# Read the dist config from $1 and write a dry-run variant to ${dist_config},
# injecting dispatch-releases/pr-run-mode/tag-namespace into the [dist] section.
# The tag-namespace defaults to ${dry_run_tag_namespace} but can be overridden
# via $2 (used by the drift check to pick a throwaway output filename).
write_dry_run_dist_config() {
  local source_config="$1"
  local tag_namespace="${2:-${dry_run_tag_namespace}}"

  awk -v tag_namespace="${tag_namespace}" '
    BEGIN {
      in_dist = 0
      inserted = 0
    }

    function insert_settings() {
      if (!inserted) {
        print "dispatch-releases = true"
        print "pr-run-mode = \"skip\""
        print "tag-namespace = \"" tag_namespace "\""
        inserted = 1
      }
    }

    /^\[dist\]$/ {
      in_dist = 1
      print
      next
    }

    /^\[/ && in_dist {
      insert_settings()
      in_dist = 0
    }

    in_dist && /^(dispatch-releases|pr-run-mode|tag-namespace)[[:space:]]*=/ {
      next
    }

    { print }

    END {
      if (in_dist) {
        insert_settings()
      }
    }
  ' "${source_config}" > "${dist_config}"
}

# Apply the deterministic safety edits to the dry-run workflow at $1. The header
# text hardcodes the canonical "dist-dry-run" namespace regardless of the
# namespace actually used to generate the file, so the committed workflow and a
# drift-check regeneration produce identical output.
apply_dry_run_safety_overlay() {
  local workflow="$1"

  perl -0pi -e '
    s/\A(# This file was autogenerated[^\n]*\n)#\n/$1# It was generated with temporary dry-run settings:\n# dispatch-releases = true, pr-run-mode = "skip", tag-namespace = "dist-dry-run".\n# The workflow name, permissions, and non-dry-run input guard are deterministic safety edits applied by .github\/scripts\/regen-dist-release.sh.\n#\n/s;
    s/^name: Release$/name: cargo-dist Dry Run/m;
    s/    permissions:\n      "attestations": "write"\n      "contents": "write"\n      "id-token": "write"/    permissions:\n      "contents": "read"/g;
    s/"contents": "write"/"contents": "read"/g;
    s/description: Release Tag/description: Dry-run sentinel. Leave as dry-run; real tags are refused./;
    s/(\n      - uses: actions\/checkout\@v6\n        with:\n          persist-credentials: false\n          submodules: recursive\n)(      - name: Install dist\n)/$1      - name: Refuse real release tags\n        if: \${{ inputs.tag != '\''dry-run'\'' }}\n        run: |\n          echo "::error::This workflow is only for cargo-dist dry runs. Leave the tag input set to dry-run."\n          exit 1\n$2/s;
  ' "${workflow}"

  if grep -Eq '^[[:space:]]+"[^"]+": "write"[[:space:]]*$' "${workflow}"; then
    echo "Dry-run workflow still contains write permissions after applying the safety overlay" >&2
    return 1
  fi
}
